name: Build and Push Docker Image and deploy to elastic beanstalk

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up AWS CLI
        uses: aws-actions/aws-cli-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build Docker image
#        run: |
#          docker build -t tmsasikumar/emotion_image_recognition:latest .
#
#      - name: Push Docker image
#        run: |
#          docker push tmsasikumar/emotion_image_recognition:latest

      - name: Deploy to Elastic Beanstalk
        run:
          eb deploy --region ${{ secrets.AWS_REGION }} --application-name mood-docker--environment-name Mood-docker-env 